// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ieubywemkmymoynbivay.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlldWJ5d2Vta215bW95bmJpdmF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwMzgxNTEsImV4cCI6MjA3NDYxNDE1MX0.EdrmBxZZ4sXxD71-JPdbLYV_ZK0smcnbERoix37CLJM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});